set -g status-right-length 120
set -g status-right "#(status)"
set -s copy-command "xsel -i"
set -g destroy-unattached
bind u run "tmux capture-pane; tmux show-buffer | dmenu-urlselect | xargs open-url"
