# Use Ctrl+F as lead key
unbind C-b
set -g prefix C-f
bind-key -n C-f send-prefix

# Status bar with external command
set -g status-right-length 120
set -g status-right "#(status)"

# Copy to clipboard, not only the tmux buffer
set -s copy-command "xsel -ib"

# Destroy unattached session (use only as multiplexer)
set -g destroy-unattached

# Select and prompt for opening URLs on lead + U with external command
bind u run "tmux capture-pane; tmux show-buffer | dmenu-urlselect | xargs open-url"
