# Unbind all keys (except copy-mode)
unbind -a -T prefix
unbind -a -T root

# Custom bindings
set -g prefix C-f
bind-key -n C-f send-prefix
bind-key f command-prompt
bind-key \' split-window -v -c "#{pane_current_path}"
bind-key \; split-window -h -c "#{pane_current_path}"
bind-key l select-pane -R
bind-key C-l resize-pane -R
bind-key h select-pane -L
bind-key C-h resize-pane -L
bind-key j select-pane -D
bind-key C-j resize-pane -D
bind-key k select-pane -U
bind-key C-k resize-pane -U
bind-key [ copy-mode
bind-key ] paste-buffer
bind-key o new-window
bind-key n next-window
bind-key p previous-window
bind-key i break-pane

# Status bar with external command
set -g status-right-length 120
set -g status-right "#(status)"

# Copy to clipboard, not only the tmux buffer
set -s copy-command "xsel -ib"

# Destroy unattached session (use only as multiplexer)
set -g destroy-unattached

# Select and prompt for opening URLs on lead + U with external command
#bind u run "tmux capture-pane -J; tmux show-buffer | dmenu-urlselect | xargs open-url"
bind u {
	capture-pane -J
	display-popup -w 50% -T "Open URL" -E "tmux show-buffer | dmenu-urlselect -m fzf | xargs open-url; sleep 0.1"
}
