#!/bin/sh

# Install and remove packages from a configuration file.

# Usage: apkworld [file]
# Requires: apk (Alpine Linux package manager), doas (or sudo)

PACKAGES="${1:-$HOME/.config/alpine-packages}"
SUDO_CMD=doas

tmp_file=$(mktemp)
doas cp /etc/apk/world /etc/apk/world.backup
cat "$PACKAGES" | sed 's/#.*//' | grep -v '^[:space:]*$' > $tmp_file
doas mv $tmp_file /etc/apk/world
doas apk fix -U --interactive
